import { db } from "../server/db";
import { works } from "../server/schema";

const DEMO = [
  { slug:"the-red-void", title:"The Red Void", tCode:"T2026-W18", sovereignId:"666-042", phaseId:60607, medium:"MB4; MB5; MB6 — Carbon black ink, sumi, graphite", dimensions:"97×180 cm", rating:4, disposition:"SA", weekNumber:18, technicalObservation:JSON.stringify({ambient_context:{steps:4554,heart_rate:72,energy:"hot",jester:0,walking:false,sciatica:true,rest_days:1,mega_walk:false},matrix_flags:{is_kill:false,is_save:true},week_number:18,date_info:{date:"2026-04-03",weekday:"Friday"},surfaces:"S11",mediums:"MB4; MB5; MB6",tools:"T2; T1",technical_observation:"First production work on S11. Surface held the ink with unexpected density.",self_directive:"Do not look back. The warmup is over.",discovery:"S11 accepts wet-on-wet layering without bleed."})},
  { slug:"songkran-silence", title:"Songkran Silence", tCode:"T2026-W10", sovereignId:"666-089", phaseId:60606, medium:"MB1; MB2; MB3 — India ink, charcoal, pencil", dimensions:"50×100 cm", rating:2, disposition:"TR", weekNumber:10, technicalObservation:JSON.stringify({ambient_context:{steps:22100,heart_rate:68,energy:"depleted",jester:2,walking:true,sciatica:false,rest_days:0,mega_walk:true},matrix_flags:{is_kill:true,is_save:false},week_number:10,date_info:{date:"2026-03-14",weekday:"Saturday"},surfaces:"S3",mediums:"MB1; MB2; MB3",tools:"T1",technical_observation:"Made during Songkran. Paper damp from humidity. Ink spread unpredictably."})},
  { slug:"chanel-blue", title:"Chanel Blue", tCode:"T2026-W19", sovereignId:"666-273", phaseId:60607, medium:"MC2; MC4; MC5 — Cobalt, ultramarine, cerulean", dimensions:"70×140 cm", rating:3, disposition:"SA", weekNumber:19, technicalObservation:JSON.stringify({ambient_context:{steps:12000,heart_rate:65,energy:"sustainable",jester:0,walking:false,sciatica:false,rest_days:3,mega_walk:false},matrix_flags:{is_kill:false,is_save:false},week_number:19,date_info:{date:"2026-04-28",weekday:"Tuesday"},surfaces:"S6",mediums:"MC2; MC4; MC5",tools:"T2",technical_observation:"Commission piece. Color work is rare — only 9 instances in the archive.",discovery:"Color on S6 requires 2x drying time."})},
  { slug:"genesis-seed", title:"Genesis Seed", tCode:"T2026-W01", sovereignId:"666-001", phaseId:60606, medium:"MB1; MB3 — India ink, pencil", dimensions:"50×100 cm", rating:1, disposition:"TR", weekNumber:1, technicalObservation:JSON.stringify({ambient_context:{steps:8500,heart_rate:70,energy:"depleted",jester:0,walking:false,sciatica:true,rest_days:2,mega_walk:false},matrix_flags:{is_kill:true,is_save:false},week_number:1,date_info:{date:"2025-12-29",weekday:"Monday"},surfaces:"S1",mediums:"MB1; MB3",tools:"T1",technical_observation:"The first work. 22 days of silence followed. S1 is 100×200 cm — largest surface, used only once.",self_directive:"Start. Anything. Just start.",discovery:"S1 is too large for the current hand. Scale down."})},
  { slug:"the-eruption", title:"The Eruption", tCode:"T2026-W16", sovereignId:"666-183", phaseId:60607, medium:"MB4; MB5; MB6 — Carbon black, sumi, graphite", dimensions:"97×180 cm", rating:5, disposition:"SA", weekNumber:16, technicalObservation:JSON.stringify({ambient_context:{steps:3800,heart_rate:74,energy:"hot",jester:1,walking:false,sciatica:false,rest_days:1,mega_walk:false},matrix_flags:{is_kill:false,is_save:true},week_number:16,date_info:{date:"2026-04-08",weekday:"Wednesday"},surfaces:"S11",mediums:"MB4; MB5; MB6",tools:"T2; T1",technical_observation:"Week 16 — gravitational center. 37 works, 64.60 m². Work 183 at 2:47 AM. Hand was autonomous.",self_directive:"Let the hand decide. The mind has done enough.",discovery:"Sustained production possible when substrate, medium, and body align."})},
  { slug:"sciatica-palimpsest", title:"Sciatica Palimpsest", tCode:"T2026-W05", sovereignId:"666-045", phaseId:60606, medium:"MB1; MB2 — India ink, charcoal", dimensions:"70×180 cm", rating:2, disposition:"SA", weekNumber:5, technicalObservation:JSON.stringify({ambient_context:{steps:6200,heart_rate:78,energy:"depleted",jester:0,walking:false,sciatica:true,rest_days:0,mega_walk:false},matrix_flags:{is_kill:false,is_save:false},week_number:5,date_info:{date:"2026-02-02",weekday:"Monday"},surfaces:"S4",mediums:"MB1; MB2",tools:"T1",technical_observation:"Sciatica week. Back pain radiated into shoulder, altered stroke angle. Work visibly asymmetric.",weekly_narrative:{somatic_state:"Painful."}})},
  { slug:"hanoi-cafe", title:"Hanoi Cafe", tCode:"T2026-W02", sovereignId:"666-012", phaseId:60606, medium:"MB1; MB3 — India ink, pencil", dimensions:"50×100 cm", rating:1, disposition:"TR", weekNumber:2, technicalObservation:JSON.stringify({ambient_context:{steps:99285,heart_rate:62,energy:"hot",jester:0,walking:true,sciatica:false,rest_days:0,mega_walk:true},matrix_flags:{is_kill:true,is_save:false},week_number:2,date_info:{date:"2026-01-20",weekday:"Tuesday"},surfaces:"S5",mediums:"MB1; MB3",tools:"T1",technical_observation:"Hanoi cafe. 99,285 steps that week. 11 works across S5/S6, 83.3% kill rate.",walking_insights:"Motorbike rides have the same mental effect as walking."})},
  { slug:"rest-week-return", title:"Rest Week Return", tCode:"T2026-W20", sovereignId:"666-294", phaseId:60607, medium:"MB4; MB5 — Carbon black, sumi", dimensions:"97×180 cm", rating:3, disposition:"SA", weekNumber:20, technicalObservation:JSON.stringify({ambient_context:{steps:null,heart_rate:null,energy:null,jester:null,walking:null,sciatica:null,rest_days:null,mega_walk:null},matrix_flags:{is_kill:false,is_save:false},week_number:20,date_info:{date:"2026-05-07",weekday:"Thursday"},surfaces:"S12",mediums:"MB4; MB5",tools:"T2; T1",technical_observation:"Final work. 19 works on S12 in one day. Week 20 has no ambient roundup — the live edge.",discovery:"S12 smells bad when wet. But holds production ink beautifully."})},
  { slug:"march-fourteen", title:"March Fourteen — Ritual Density", tCode:"T2026-W12", sovereignId:"666-127", phaseId:60606, medium:"MB2; MB3 — Charcoal, pencil", dimensions:"70×140 cm", rating:2, disposition:"PT", weekNumber:12, technicalObservation:JSON.stringify({ambient_context:{steps:15400,heart_rate:71,energy:"sustainable",jester:1,walking:true,sciatica:true,rest_days:0,mega_walk:false},matrix_flags:{is_kill:false,is_save:false},week_number:12,date_info:{date:"2026-03-14",weekday:"Saturday"},surfaces:"S3",mediums:"MB2; MB3",tools:"T1",technical_observation:"March 14 — 28 works in one day. Largest same-day cluster. Made at 11:47 PM, work 127 of the day."})},
  { slug:"save-has-potential", title:"Save Has Potential", tCode:"T2026-W08", sovereignId:"666-089", phaseId:60606, medium:"MB1; MB2; MB3 — India ink, charcoal, pencil", dimensions:"70×180 cm", rating:2, disposition:"SHP", weekNumber:8, technicalObservation:JSON.stringify({ambient_context:{steps:8900,heart_rate:69,energy:"sustainable",jester:0,walking:false,sciatica:true,rest_days:1,mega_walk:false},matrix_flags:{is_kill:false,is_save:false},week_number:8,date_info:{date:"2026-02-21",weekday:"Saturday"},surfaces:"S7",mediums:"MB1; MB2; MB3",tools:"T1",technical_observation:"SHP flag — one of only 5 in archive. S7 is 'incredibly fragile'. Made with light hand.",save_has_potential:true})},
];

async function seed() {
  console.log("🌱 Seeding demo works...\n");
  let inserted = 0, skipped = 0;
  for (const w of DEMO) {
    try { await db.insert(works).values(w); console.log(`   ✅ ${w.sovereignId}_${w.tCode}`); inserted++; }
    catch (err: any) {
      if (err.code === "ER_DUP_ENTRY") { console.log(`   ⏭️  ${w.sovereignId}_${w.tCode}`); skipped++; }
      else console.error(`   ❌ ${w.sovereignId}_${w.tCode}: ${err.message}`);
    }
  }
  console.log(`\n🚀 Seed complete: ${inserted} inserted, ${skipped} skipped`);
  process.exit(0);
}
seed().catch(err => { console.error("\n❌ Seed failed:", err.message); process.exit(1); });
